services:
  subscription_handler:
    build: .
    container_name: peopleinespace_subscription_handler
    image: peopleinespace:latest
    env_file:
      - /app/.env
    volumes:
      - ~/peopleinspace-bot/app/logs:/app/logs
      - ~/peopleinspace-bot/app/users.json:/app/users.json
    restart: always

  send_update:

    container_name: peopleinespace_send_update
    image: peopleinespace:latest
    build: .
    command: python src/send_update.py
    env_file:
      - /app/.env
    volumes:
      - ~/peopleinspace-bot/app/logs:/app/logs
      - ~/peopleinspace-bot/app/users.json:/app/users.json
