services:
  subscription_handler:
    build: .
    container_name: subscription_handler
    image: peopleinespace/subscription_handler:latest
    environment:
      - TZ=Asia/Jerusalem
    #    volumes:
    #      - ~/peopleinspace-bot:/app
    restart: always

  send_update:
    build: .
    container_name: send_update
    image: peopleinespace/send_update:latest

    command:
      - python src/send_update.py
    environment:
      - TZ=Asia/Jerusalem
    #    volumes:
    #      - ~/peopleinspace-bot:/app
    restart: always
