version: '2'
services:
  subscription_handler:
    build: .
    container_name: peopleinespace_subscription_handler
    image: peopleinespace:latest
    env_file:
      - .env
    volumes:
      #TODO:
      - /home/pi/peopleinspace-bot/app/logs:/app/logs
      - /home/pi/peopleinspace-bot/app/users.json:/app/users.json
    restart: always

  send_update:

    container_name: peopleinespace_send_update
    image: peopleinespace:latest
    build: .
    command: python src/send_update.py
    env_file:
      - .env
    volumes:
      - /home/pi/peopleinspace-bot/app/logs:/app/logs
      - /home/pi/peopleinspace-bot/app/users.json:/app/users.json
