/* groovylint-disable CompileStatic, SimpleDateFormatMissingLocale */
import java.text.SimpleDateFormat

REPOSITORY = 'peopleinespace'
ENV = 'prod'
def IMAGE_TAG

pipeline {
    agent any
    stages {
        stage('Pre Build') {
            steps {
                script {
                    echo 'Pre Build started'
                    // ~ : /var/lib/jenkins
                    sh "mkdir -p ~/${REPOSITORY}-bot/app/logs/"
                    sh "touch ~/${REPOSITORY}-bot/app/users.json"
                    echo 'Pre Build completed'
                }
            }
        }
        stage('Build') {
            steps {
                withCredentials([file(credentialsId: 'peopleinspace.envPROD', variable: 'ENV_FILE')]) {
                    sh('cat $ENV_FILE > .env')
                }
                script {
                    sh '''hostname
                    lsb_release -a
                    pwd
                    ls -a'''
                    def now = new Date()
                    sdf = new SimpleDateFormat('MMddyyHHmmss')
                    timestamp = sdf.format(now)
                    IMAGE_TAG = ENV + '-' + env.BUILD_ID
                    echo 'Build started'
                    echo 'Building the Docker image...'
                    sh "docker build -t $REPOSITORY:latest ."
                    sh "docker tag $REPOSITORY:latest $REPOSITORY:$IMAGE_TAG"
                    echo 'Build completed'
                }
            }
            post {
                success {
                    echo 'Build success'
                }
            }
        }
        stage('Pre Deploy') {
            steps {
                script {

                    echo 'Pre Deploy started'

                    // stop and remove subscription_handler container
                    sh 'docker stop peopleinespace_subscription_handler || true'
                    sh 'docker rm peopleinespace_subscription_handler || true'
                    
                    // stop and remove send_update container
                    sh 'docker stop peopleinespace_send_update || true'
                    sh 'docker rm peopleinespace_send_update || true'

                    // remove relevant images
                    def tags_to_delete = sh(script: "docker images --format {{.Repository}}:{{.Tag}} | grep $REPOSITORY:$ENV-", returnStdout: true)
                    keep_tag = REPOSITORY + ':' + IMAGE_TAG
                    tags_to_delete = tags_to_delete.replaceAll(keep_tag, '')
                    tags_to_delete = tags_to_delete.replaceAll('\n', ' ')
                    sh "docker rmi ${tags_to_delete} || true"

                    echo 'Pre Deploy completed'
                }
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploy started'
                echo 'Deploying the Docker image..'

                // subscription_handler //
                sh 'docker compose up -d subscription_handler'
                sh 'docker logs peopleinespace_subscription_handler'

                // send_update //
                sh 'docker compose create send_update'
                echo 'Deploy completed'
            }
        }
    }
}