/* groovylint-disable CompileStatic, SimpleDateFormatMissingLocale */
import java.text.SimpleDateFormat

REPOSITORY = 'peopleinespace'
ENV = 'prod'
def IMAGE_TAG
pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                withCredentials([file(credentialsId: 'peopleinspace.envPROD', variable: 'ENV_FILE')]) {
                    sh('cat $ENV_FILE > .env')
                }
                script {
                    sh '''hostname
                    lsb_release -a
                    pwd
                    ls -a'''
                    def now = new Date()
                    sdf = new SimpleDateFormat('MMddyyHHmmss')
                    timestamp = sdf.format(now)
                    IMAGE_TAG = ENV + '-' + timestamp
                    echo 'Build started'
                    echo 'Building the Docker image...'
                    sh "docker build -t $REPOSITORY:latest ."
                    sh "docker tag $REPOSITORY:latest $REPOSITORY:$IMAGE_TAG"
                    echo 'Build completed'
                }
            }
            post {
                success {
                    echo 'Build success'
                }
            }
        }
        stage('Pre Deploy') {
            steps {
                echo 'Pre Deploy started'

                // stop and remove subscription_handler container
                sh 'docker stop peopleinespace_subscription_handler || echo "No container to stop"'
                sh 'docker rm peopleinespace_subscription_handler || echo "No container to remove"'
                
                // stop and remove send_update container
                sh 'docker stop peopleinespace_send_update || echo "No container to stop"'
                sh 'docker rm peopleinespace_send_update || echo "No container to remove"'

                // remove relevant images
                sh 'docker rmi $(docker images | grep $REPOSITORY:$ENV || echo "No image to remove"'


                echo 'Pre Deploy completed'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploy started'
                echo 'Deploying the Docker image..'

                // subscription_handler //
                sh 'docker compose up -d subscription_handler'
                // docker logs peopleinespace_subscription_handler

                // send_update //
                // docker-compose up -d send_update
                // docker logs peopleinespace_send_update
                echo 'Deploy completed'
            }
        }
    }
}