/* groovylint-disable CompileStatic, SimpleDateFormatMissingLocale */
import java.text.SimpleDateFormat

REPOSITORY = 'peopleinespace'
PROJECT_PATH = "/home/jenkins/$REPOSITORY"
ENV = 'dev'

pipeline {
    agent { label 'raspi-slave1-agent' }
    stages {
        stage('Pre Build') {
            steps {
                echo 'Pre Build started'
                echo 'Pre Build completed'
            }
        }
        stage('Build') {
            steps {
                withCredentials([file(credentialsId: 'peopleinspace.envrcDEV', variable: 'ENVRC_FILE')]) {
                    sh('cat $ENVRC_FILE > .envrc')
                }
                script {
                    sh '''#!/bin/bash
                    hostname
                    lsb_release -a
                    pwd
                    ls -a
                    '''
                    sh 'pip3 install -r requirements.txt'
                    echo 'Build completed'
                }
            }
            post {
                success {
                    echo 'Build success'
                }
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploy started'
                echo 'send_update cronjob 0800AM at crontab -e'
                echo  ""
                echo "################################################"
                echo ""
                echo "peopleinespace_subscription_handler bot at /etc/rc.local startup as screen'"
                echo "Kill current peopleinespace_subscription_handler bot screen sesssion"
                sh 'screen -X -S peopleinespace_subscription_handler quit || echo "No screen session to kill"'
                echo 'Runnning rc.local after changes'

                sh '''#!/bin/bash
                    set +x
                    . /etc/rc.local
                    '''
                echo 'Deploy completed'
            }
        }
    }
}
